export const ADMISSION_STUDENT_INFO = "ADMISSION_STUDENT_INFO";
export const ADMISSION_STUDENT_GUARDIAN = "ADMISSION_STUDENT_GUARDIAN";
export const ADMISSION_STUDENT_PRE_SCHOOL = "ADMISSION_STUDENT_PRE_SCHOOL";